apiVersion: v1
kind: Service
metadata:
  name: kflask-service
spec:
  selector:
    app: kflask
  type: LoadBalancer  
  ports:
  - protocol: TCP
    nodePort: 30300
    port: 3030
    targetPort: 80
